import { makeStyles } from '@material-ui/core/styles';

export const formPageOneStyles = makeStyles((theme) => ({
    root: {
        display: 'flex',
        justifyContent: 'center',
        width: '100%',
        [theme.breakpoints.down('800')]: {
            flexDirection: 'column',
            width: '95%',
        },
    },
    leftContainer: {
        width: '50%',
        [theme.breakpoints.down('1000')]: {
            marginLeft: '5%',
        },
        [theme.breakpoints.down('800')]: {
            display: 'flex',
            flexDirection: 'column',
            justifyContent: 'center',
            width: '90%',
        },
    },
    inputDiv: {
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'space-between',
        border: '2px solid #f0f0f0',
        borderRadius: '15px',
        margin: '40px 0',
        padding: '10px 15px',
        [theme.breakpoints.down('800')]: {
            margin: '20px 0',
        },
    },
    input: {
        height: '35px',
        border: 'none',
        borderRadius: '15px',
        outline: 'none',
        fontSize: '1.6rem',
        width: '90%',
    },
    geo: {
        width: '90%',
    },
    label: {
        color: '#b7b7b7',
        fontSize: '1.6rem',
        marginRight: '6px',
    },
    textArea: {
        height: '150px',
        border: '2px dashed #f0f0f0',
        borderRadius: '15px',
        outline: 'none',
        padding: '10px 12px',
        fontSize: '1.6rem',
        width: '94%',
        [theme.breakpoints.down('800')]: {
            width: '95%',
            margin: '20px 0',
        },
        [theme.breakpoints.down('600')]: {
            width: '93%',
        },
    },
    rightContainer: {
        width: '40%',
        marginLeft: '5%',
        paddingRight: '30px',
        [theme.breakpoints.down('800')]: {
            display: 'flex',
            flexDirection: 'column',
            width: '90%',
            paddingRight: '0',
        },
    },
    timeDiv: {
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'space-around',
        border: '2px solid #f0f0f0',
        borderRadius: '15px',
        margin: '40px 0',
        [theme.breakpoints.down('800')]: {
            margin: '20px 0',
        },
    },
    date: {
        border: 'none',
        borderRadius: '15px',
        color: 'black',
        padding: '12px 30px',
        fontSize: '1.6rem',
    },
    timeDiv: {
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'space-around',
        border: '2px solid #f0f0f0',
        borderRadius: '15px',
        margin: '40px 0',
        [theme.breakpoints.down('800')]: {
            margin: '20px 0',
        },
    },
    select: {
        display: 'flex',
        alignItems: 'center',
        margin: '10px 5px',
        opacity: '0.75',
        borderRadius: '5px',
        color: 'white',
        padding: '5px 20px',
        border: 'none',
        borderBottom: 'none',
        fontSize: '1.4rem',
    },
    categoryDiv: {
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'space-around',
        border: '2px solid #f0f0f0',
        borderRadius: '15px',
        color: '#b7b7b7',
        margin: '40px 0',
        padding: '7px',
        [theme.breakpoints.down('800')]: {
            margin: '20px 0',
        },
    },
    category: {
        display: 'flex',
        alignItems: 'center',
        borderRadius: '15px',
        marginLeft: '5%',
        background: 'white',
        fontSize: '1.6rem',
        padding: '5px 30px',
        outline: 'none',
        color: 'black',
    },
    buttonContainer: {
        display: 'flex',
        justifyContent: 'flex-end',
        marginRight: '5%',
        marginBottom: '20px',
        width: '100%',
        [theme.breakpoints.down('800')]: {
            marginRight: '0',
            justifyContent: 'center',
            alignItems: 'center',
        },
    },
    leftBtn: {
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        border: '2px solid #e5e5e5',
        background: 'rgba(255, 255, 255, 0.5)',
        padding: '15px 20px',
        borderRadius: '15px',
        margin: '20px 20px',
        color: '#b3b3b3',
        outline: 'none',
        fontSize: '2rem',
        fontWeight: 'bold',
        width: '15%',
        [theme.breakpoints.down('800')]: {
            width: '30%',
        },
    },
    rightBtn: {
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        background: '#58d473',
        boxShadow: '0px 4px 10px rgba(0, 0, 0, 0.05)',
        padding: '15px 20px',
        borderRadius: '15px',
        margin: '20px 0',
        color: 'white',
        outline: 'none',
        fontSize: '2rem',
        fontWeight: 'bold',
        width: '15%',
        [theme.breakpoints.down('800')]: {
            width: '30%',
        },
    },
}));
